name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm" # cache based on pnpm-lock.yaml

      # Install & activate pnpm via Corepack (recommended by pnpm docs)
      - run: corepack enable
      - run: corepack prepare pnpm@9 --activate
      - run: pnpm -v # sanity check: should print pnpm version

      - run: pnpm install --frozen-lockfile
      - run: pnpm build # generates out/
      - name: Disable Jekyll
        run: touch out/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
